### PR TITLE
fix ties over breaks on dotted notes

### LINKED ISSUE #1718: Tie + augmentation dot + system break interaction
When a tie crosses a system break, the tie start will collide with augmentation dots on the starting note for the tie.  In other words, the dot-avoidance code for ties is not being called when the tie goes over a system break:

Screen Shot 2020-10-03 at 6 21 40 AM

MEI test data:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2020-10-03T06:24:27" version="3.0.0-dev-f0996ca-dirty">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="mdiv-0000001384622065">
    <score xml:id="score-0000001262513604">
     <scoreDef xml:id="scoredef-0000000830027336" midi.bpm="400">
      <staffGrp xml:id="staffgrp-0000000003742673">
       <staffDef xml:id="staffdef-0000002084676771" n="1" lines="5">
        <clef xml:id="clef-0000000718382857" shape="G" line="2" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1" n="1">
       <staff xml:id="staff-0000001596716717" n="1">
        <layer xml:id="layer-L1F1N1" n="1">
         <note xml:id="note-L3F1" dots="1" dur="2" oct="5" pname="f" accid.ges="n" />
        </layer>
       </staff>
       <tie xml:id="tie-L3F1-L5F1" startid="#note-L3F1" endid="#note-L5F1" />
      </measure>
      <measure xml:id="measure-L4" n="2">
       <staff xml:id="staff-L4F1N1" n="1">
        <layer xml:id="layer-L4F1N1" n="1">
         <note xml:id="note-L5F1" dots="1" dur="2" oct="5" pname="f" accid.ges="n" />
        </layer>
       </staff>
       <tie xml:id="tie-L5F1-L7F1" startid="#note-L5F1" endid="#note-L7F1" />
      </measure>
      <measure xml:id="measure-L6" n="3">
       <staff xml:id="staff-L6F1N1" n="1">
        <layer xml:id="layer-L6F1N1" n="1">
         <note xml:id="note-L7F1" dots="1" dur="2" oct="5" pname="f" accid.ges="n" />
        </layer>
       </staff>
       <tie xml:id="tie-L7F1-L9F1" startid="#note-L7F1" endid="#note-L9F1" />
      </measure>
      <measure xml:id="measure-L8" n="4">
       <staff xml:id="staff-L8F1N1" n="1">
        <layer xml:id="layer-L8F1N1" n="1">
         <note xml:id="note-L9F1" dots="1" dur="2" oct="5" pname="f" accid.ges="n" />
        </layer>
       </staff>
       <tie xml:id="tie-L9F1-L11F1" startid="#note-L9F1" endid="#note-L11F1" />
      </measure>
      <measure xml:id="measure-L10" n="5">
       <staff xml:id="staff-L10F1N1" n="1">
        <layer xml:id="layer-L10F1N1" n="1">
         <note xml:id="note-L11F1" dots="1" dur="2" oct="5" pname="f" accid.ges="n" />
        </layer>
       </staff>
       <tie xml:id="tie-L11F1-L13F1" startid="#note-L11F1" endid="#note-L13F1" />
      </measure>
      <measure xml:id="measure-L12" n="6">
       <staff xml:id="staff-L12F1N1" n="1">
        <layer xml:id="layer-L12F1N1" n="1">
         <note xml:id="note-L13F1" dots="1" dur="2" oct="5" pname="f" accid.ges="n" />
        </layer>
       </staff>
       <tie xml:id="tie-L13F1-L15F1" startid="#note-L13F1" endid="#note-L15F1" />
      </measure>
      <measure xml:id="measure-L14" n="7">
       <staff xml:id="staff-L14F1N1" n="1">
        <layer xml:id="layer-L14F1N1" n="1">
         <note xml:id="note-L15F1" dots="1" dur="2" oct="5" pname="f" accid.ges="n" />
        </layer>
       </staff>
       <tie xml:id="tie-L15F1-L17F1" startid="#note-L15F1" endid="#note-L17F1" />
      </measure>
      <measure xml:id="measure-L16" n="8">
       <staff xml:id="staff-L16F1N1" n="1">
        <layer xml:id="layer-L16F1N1" n="1">
         <note xml:id="note-L17F1" dots="1" dur="2" oct="5" pname="f" accid.ges="n" />
        </layer>
       </staff>
       <tie xml:id="tie-L17F1-L19F1" startid="#note-L17F1" endid="#note-L19F1" />
      </measure>
      <measure xml:id="measure-L18" right="end" n="9">
       <staff xml:id="staff-L18F1N1" n="1">
        <layer xml:id="layer-L18F1N1" n="1">
         <note xml:id="note-L19F1" dots="1" dur="2" oct="5" pname="f" accid.ges="n" />
        </layer>
       </staff>
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

### PR DESCRIPTION
**Pull request by rettinghaus**
fixes #1718 

example file from issue by @craigsapp 
ties

### CODE REVIEW

**Comment by rettinghaus** [comment]
@craigsapp could you provide tests with tied chords?

**Comment by craigsapp** [comment]
Here is a test for chords and various notehead types.  A complication occurs for flagged notes where there is not much room left over for ties.

Current rendering (before this fix):

Screen Shot 2020-10-03 at 9 51 39 AM

Verovio options: pageWidth: 737, scale: 75

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2020-10-03T09:52:46" version="3.0.0-dev-f0996ca-dirty">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="mdiv-0000001764458295">
    <score xml:id="score-0000000652442043">
     <scoreDef xml:id="scoredef-0000001144962776" midi.bpm="400">
      <staffGrp xml:id="staffgrp-0000000515826593">
       <staffDef xml:id="staffdef-0000000790575356" n="1" lines="5">
        <clef xml:id="clef-0000000086899143" shape="G" line="2" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1" n="1">
       <staff xml:id="staff-0000001071711548" n="1">
        <layer xml:id="layer-L1F1N1" n="1">
         <chord xml:id="chord-L3F1" dots="1" dur="1">
          <note xml:id="note-L3F1S1" oct="5" pname="f" accid.ges="n" />
          <note xml:id="note-L3F1S2" oct="5" pname="d" accid.ges="n" />
          <note xml:id="note-L3F1S3" oct="4" pname="b" accid.ges="n" />
         </chord>
        </layer>
       </staff>
       <tie xml:id="tie-L3F1S1-L5F1S1" startid="#note-L3F1S1" endid="#note-L5F1S1" />
       <tie xml:id="tie-L3F1S2-L5F1S2" startid="#note-L3F1S2" endid="#note-L5F1S2" />
       <tie xml:id="tie-L3F1S3-L5F1S3" startid="#note-L3F1S3" endid="#note-L5F1S3" />
      </measure>
      <measure xml:id="measure-L4" n="2">
       <staff xml:id="staff-L4F1N1" n="1">
        <layer xml:id="layer-L4F1N1" n="1">
         <chord xml:id="chord-L5F1" dots="1" dur="1">
          <note xml:id="note-L5F1S1" oct="5" pname="f" accid.ges="n" />
          <note xml:id="note-L5F1S2" oct="5" pname="d" accid.ges="n" />
          <note xml:id="note-L5F1S3" oct="4" pname="b" accid.ges="n" />
         </chord>
        </layer>
       </staff>
       <tie xml:id="tie-L5F1S1-L7F1S1" startid="#note-L5F1S1" endid="#note-L7F1S1" />
       <tie xml:id="tie-L5F1S2-L7F1S2" startid="#note-L5F1S2" endid="#note-L7F1S2" />
       <tie xml:id="tie-L5F1S3-L7F1S3" startid="#note-L5F1S3" endid="#note-L7F1S3" />
      </measure>
      <measure xml:id="measure-L6" n="3">
       <staff xml:id="staff-L6F1N1" n="1">
        <layer xml:id="layer-L6F1N1" n="1">
         <chord xml:id="chord-L7F1" dots="1" dur="2">
          <note xml:id="note-L7F1S1" oct="5" pname="f" accid.ges="n" />
          <note xml:id="note-L7F1S2" oct="5" pname="d" accid.ges="n" />
          <note xml:id="note-L7F1S3" oct="4" pname="b" accid.ges="n" />
         </chord>
         <chord xml:id="chord-L8F1" dots="1" dur="2">
          <note xml:id="note-L8F1S1" oct="5" pname="f" accid.ges="n" />
          <note xml:id="note-L8F1S2" oct="5" pname="d" accid.ges="n" />
          <note xml:id="note-L8F1S3" oct="4" pname="b" accid.ges="n" />
         </chord>
        </layer>
       </staff>
       <tie xml:id="tie-L7F1S1-L8F1S1" startid="#note-L7F1S1" endid="#note-L8F1S1" />
       <tie xml:id="tie-L7F1S2-L8F1S2" startid="#note-L7F1S2" endid="#note-L8F1S2" />
       <tie xml:id="tie-L7F1S3-L8F1S3" startid="#note-L7F1S3" endid="#note-L8F1S3" />
       <tie xml:id="tie-L8F1S1-L10F1S1" startid="#note-L8F1S1" endid="#note-L10F1S1" />
       <tie xml:id="tie-L8F1S2-L10F1S2" startid="#note-L8F1S2" endid="#note-L10F1S2" />
       <tie xml:id="tie-L8F1S3-L10F1S3" startid="#note-L8F1S3" endid="#note-L10F1S3" />
      </measure>
      <measure xml:id="measure-L9" n="4">
       <staff xml:id="staff-L9F1N1" n="1">
        <layer xml:id="layer-L9F1N1" n="1">
         <chord xml:id="chord-L10F1" dots="1" dur="2">
          <note xml:id="note-L10F1S1" oct="5" pname="f" accid.ges="n" />
          <note xml:id="note-L10F1S2" oct="5" pname="d" accid.ges="n" />
          <note xml:id="note-L10F1S3" oct="4" pname="b" accid.ges="n" />
         </chord>
         <chord xml:id="chord-L11F1" dots="1" dur="2">
          <note xml:id="note-L11F1S1" oct="5" pname="f" accid.ges="n" />
          <note xml:id="note-L11F1S2" oct="5" pname="d" accid.ges="n" />
          <note xml:id="note-L11F1S3" oct="4" pname="b" accid.ges="n" />
         </chord>
        </layer>
       </staff>
       <tie xml:id="tie-L10F1S1-L11F1S1" startid="#note-L10F1S1" endid="#note-L11F1S1" />
       <tie xml:id="tie-L10F1S2-L11F1S2" startid="#note-L10F1S2" endid="#note-L11F1S2" />
       <tie xml:id="tie-L10F1S3-L11F1S3" startid="#note-L10F1S3" endid="#note-L11F1S3" />
       <tie xml:id="tie-L11F1S1-L13F1S1" startid="#note-L11F1S1" endid="#note-L13F1S1" />
       <tie xml:id="tie-L11F1S2-L13F1S2" startid="#note-L11F1S2" endid="#note-L13F1S2" />
       <tie xml:id="tie-L11F1S3-L13F1S3" startid="#note-L11F1S3" endid="#note-L13F1S3" />
      </measure>
      <measure xml:id="measure-L12" n="5">
       <staff xml:id="staff-L12F1N1" n="1">
        <layer xml:id="layer-L12F1N1" n="1">
         <chord xml:id="chord-L13F1" dots="1" dur="1">
          <note xml:id="note-L13F1S1" oct="5" pname="f" accid.ges="n" />
          <note xml:id="note-L13F1S2" oct="5" pname="d" accid.ges="n" />
          <note xml:id="note-L13F1S3" oct="4" pname="b" accid.ges="n" />
         </chord>
        </layer>
       </staff>
       <tie xml:id="tie-L13F1S1-L15F1S1" startid="#note-L13F1S1" endid="#note-L15F1S1" />
       <tie xml:id="tie-L13F1S2-L15F1S2" startid="#note-L13F1S2" endid="#note-L15F1S2" />
       <tie xml:id="tie-L13F1S3-L15F1S3" startid="#note-L13F1S3" endid="#note-L15F1S3" />
      </measure>
      <measure xml:id="measure-L14" n="6">
       <staff xml:id="staff-L14F1N1" n="1">
        <layer xml:id="layer-L14F1N1" n="1">
         <chord xml:id="chord-L15F1" dots="1" dur="4">
          <note xml:id="note-L15F1S1" oct="5" pname="f" accid.ges="n" />
          <note xml:id="note-L15F1S2" oct="5" pname="d" accid.ges="n" />
          <note xml:id="note-L15F1S3" oct="4" pname="b" accid.ges="n" />
         </chord>
         <chord xml:id="chord-L16F1" dots="1" dur="4">
          <note xml:id="note-L16F1S1" oct="5" pname="f" accid.ges="n" />
          <note xml:id="note-L16F1S2" oct="5" pname="d" accid.ges="n" />
          <note xml:id="note-L16F1S3" oct="4" pname="b" accid.ges="n" />
         </chord>
         <chord xml:id="chord-L17F1" dots="1" dur="4">
          <note xml:id="note-L17F1S1" oct="5" pname="f" accid.ges="n" />
          <note xml:id="note-L17F1S2" oct="5" pname="d" accid.ges="n" />
          <note xml:id="note-L17F1S3" oct="4" pname="b" accid.ges="n" />
         </chord>
         <chord xml:id="chord-L18F1" dots="1" dur="4">
          <note xml:id="note-L18F1S1" oct="5" pname="f" accid.ges="n" />
          <note xml:id="note-L18F1S2" oct="5" pname="d" accid.ges="n" />
          <note xml:id="note-L18F1S3" oct="4" pname="b" accid.ges="n" />
         </chord>
        </layer>
       </staff>
       <tie xml:id="tie-L15F1S1-L16F1S1" startid="#note-L15F1S1" endid="#note-L16F1S1" />
       <tie xml:id="tie-L15F1S2-L16F1S2" startid="#note-L15F1S2" endid="#note-L16F1S2" />
       <tie xml:id="tie-L15F1S3-L16F1S3" startid="#note-L15F1S3" endid="#note-L16F1S3" />
       <tie xml:id="tie-L16F1S1-L17F1S1" startid="#note-L16F1S1" endid="#note-L17F1S1" />
       <tie xml:id="tie-L16F1S2-L17F1S2" startid="#note-L16F1S2" endid="#note-L17F1S2" />
       <tie xml:id="tie-L16F1S3-L17F1S3" startid="#note-L16F1S3" endid="#note-L17F1S3" />
       <tie xml:id="tie-L17F1S1-L18F1S1" startid="#note-L17F1S1" endid="#note-L18F1S1" />
       <tie xml:id="tie-L17F1S2-L18F1S2" startid="#note-L17F1S2" endid="#note-L18F1S2" />
       <tie xml:id="tie-L17F1S3-L18F1S3" startid="#note-L17F1S3" endid="#note-L18F1S3" />
       <tie xml:id="tie-L18F1S1-L20F1S1" startid="#note-L18F1S1" endid="#note-L20F1S1" />
       <tie xml:id="tie-L18F1S2-L20F1S2" startid="#note-L18F1S2" endid="#note-L20F1S2" />
       <tie xml:id="tie-L18F1S3-L20F1S3" startid="#note-L18F1S3" endid="#note-L20F1S3" />
      </measure>
      <measure xml:id="measure-L19" n="7">
       <staff xml:id="staff-L19F1N1" n="1">
        <layer xml:id="layer-L19F1N1" n="1">
         <chord xml:id="chord-L20F1" dots="1" dur="1">
          <note xml:id="note-L20F1S1" oct="5" pname="f" accid.ges="n" />
          <note xml:id="note-L20F1S2" oct="5" pname="d" accid.ges="n" />
          <note xml:id="note-L20F1S3" oct="4" pname="b" accid.ges="n" />
         </chord>
        </layer>
       </staff>
       <tie xml:id="tie-L20F1S1-L22F1S1" startid="#note-L20F1S1" endid="#note-L22F1S1" />
       <tie xml:id="tie-L20F1S2-L22F1S2" startid="#note-L20F1S2" endid="#note-L22F1S2" />
       <tie xml:id="tie-L20F1S3-L22F1S3" startid="#note-L20F1S3" endid="#note-L22F1S3" />
      </measure>
      <measure xml:id="measure-L21" n="8">
       <staff xml:id="staff-L21F1N1" n="1">
        <layer xml:id="layer-L21F1N1" n="1">
         <chord xml:id="chord-L22F1" dots="1" dur="2">
          <note xml:id="note-L22F1S1" oct="5" pname="f" accid.ges="n" />
          <note xml:id="note-L22F1S2" oct="5" pname="d" accid.ges="n" />
          <note xml:id="note-L22F1S3" oct="4" pname="b" accid.ges="n" />
         </chord>
         <chord xml:id="chord-L23F1" dots="1" dur="4">
          <note xml:id="note-L23F1S1" oct="5" pname="f" accid.ges="n" />
          <note xml:id="note-L23F1S2" oct="5" pname="d" accid.ges="n" />
          <note xml:id="note-L23F1S3" oct="4" pname="b" accid.ges="n" />
         </chord>
         <chord xml:id="chord-L24F1" dots="1" dur="8">
          <note xml:id="note-L24F1S1" oct="5" pname="f" accid.ges="n" />
          <note xml:id="note-L24F1S2" oct="5" pname="d" accid.ges="n" />
          <note xml:id="note-L24F1S3" oct="4" pname="b" accid.ges="n" />
         </chord>
         <chord xml:id="chord-L25F1" dots="1" dur="8" stem.dir="up">
          <note xml:id="note-L25F1S1" oct="5" pname="f" accid.ges="n" />
          <note xml:id="note-L25F1S2" oct="5" pname="d" accid.ges="n" />
          <note xml:id="note-L25F1S3" oct="4" pname="b" accid.ges="n" />
         </chord>
        </layer>
       </staff>
       <tie xml:id="tie-L22F1S1-L23F1S1" startid="#note-L22F1S1" endid="#note-L23F1S1" />
       <tie xml:id="tie-L22F1S2-L23F1S2" startid="#note-L22F1S2" endid="#note-L23F1S2" />
       <tie xml:id="tie-L22F1S3-L23F1S3" startid="#note-L22F1S3" endid="#note-L23F1S3" />
       <tie xml:id="tie-L23F1S1-L24F1S1" startid="#note-L23F1S1" endid="#note-L24F1S1" />
       <tie xml:id="tie-L23F1S2-L24F1S2" startid="#note-L23F1S2" endid="#note-L24F1S2" />
       <tie xml:id="tie-L23F1S3-L24F1S3" startid="#note-L23F1S3" endid="#note-L24F1S3" />
       <tie xml:id="tie-L24F1S1-L25F1S1" startid="#note-L24F1S1" endid="#note-L25F1S1" />
       <tie xml:id="tie-L24F1S2-L25F1S2" startid="#note-L24F1S2" endid="#note-L25F1S2" />
       <tie xml:id="tie-L24F1S3-L25F1S3" startid="#note-L24F1S3" endid="#note-L25F1S3" />
       <tie xml:id="tie-L25F1S1-L27F1S1" startid="#note-L25F1S1" endid="#note-L27F1S1" />
       <tie xml:id="tie-L25F1S2-L27F1S2" startid="#note-L25F1S2" endid="#note-L27F1S2" />
       <tie xml:id="tie-L25F1S3-L27F1S3" startid="#note-L25F1S3" endid="#note-L27F1S3" />
      </measure>
      <measure xml:id="measure-L26" n="9">
       <staff xml:id="staff-L26F1N1" n="1">
        <layer xml:id="layer-L26F1N1" n="1">
         <chord xml:id="chord-L27F1" dots="1" dur="1">
          <note xml:id="note-L27F1S1" oct="5" pname="f" accid.ges="n" />
          <note xml:id="note-L27F1S2" oct="5" pname="d" accid.ges="n" />
          <note xml:id="note-L27F1S3" oct="4" pname="b" accid.ges="n" />
         </chord>
        </layer>
       </staff>
       <tie xml:id="tie-L27F1S1-L29F1S1" startid="#note-L27F1S1" endid="#note-L29F1S1" />
       <tie xml:id="tie-L27F1S2-L29F1S2" startid="#note-L27F1S2" endid="#note-L29F1S2" />
       <tie xml:id="tie-L27F1S3-L29F1S3" startid="#note-L27F1S3" endid="#note-L29F1S3" />
      </measure>
      <measure xml:id="measure-L28" n="10">
       <staff xml:id="staff-L28F1N1" n="1">
        <layer xml:id="layer-L28F1N1" n="1">
         <chord xml:id="chord-L29F1" dots="1" dur="2">
          <note xml:id="note-L29F1S1" oct="5" pname="f" accid.ges="n" />
          <note xml:id="note-L29F1S2" oct="5" pname="d" accid.ges="n" />
          <note xml:id="note-L29F1S3" oct="4" pname="b" accid.ges="n" />
         </chord>
         <chord xml:id="chord-L30F1" dots="1" dur="4">
          <note xml:id="note-L30F1S1" oct="5" pname="f" accid.ges="n" />
          <note xml:id="note-L30F1S2" oct="5" pname="d" accid.ges="n" />
          <note xml:id="note-L30F1S3" oct="4" pname="b" accid.ges="n" />
         </chord>
         <beam xml:id="beam-L31F1-L32F1">
          <chord xml:id="chord-L31F1" dots="1" dur="8" stem.dir="down">
           <note xml:id="note-L31F1S1" oct="5" pname="f" accid.ges="n" />
           <note xml:id="note-L31F1S2" oct="5" pname="d" accid.ges="n" />
           <note xml:id="note-L31F1S3" oct="4" pname="b" accid.ges="n" />
          </chord>
          <chord xml:id="chord-L32F1" dots="1" dur="8">
           <note xml:id="note-L32F1S1" oct="5" pname="f" accid.ges="n" />
           <note xml:id="note-L32F1S2" oct="5" pname="d" accid.ges="n" />
           <note xml:id="note-L32F1S3" oct="4" pname="b" accid.ges="n" />
          </chord>
         </beam>
        </layer>
       </staff>
       <tie xml:id="tie-L29F1S1-L30F1S1" startid="#note-L29F1S1" endid="#note-L30F1S1" />
       <tie xml:id="tie-L29F1S2-L30F1S2" startid="#note-L29F1S2" endid="#note-L30F1S2" />
       <tie xml:id="tie-L29F1S3-L30F1S3" startid="#note-L29F1S3" endid="#note-L30F1S3" />
       <tie xml:id="tie-L30F1S1-L31F1S1" startid="#note-L30F1S1" endid="#note-L31F1S1" />
       <tie xml:id="tie-L30F1S2-L31F1S2" startid="#note-L30F1S2" endid="#note-L31F1S2" />
       <tie xml:id="tie-L30F1S3-L31F1S3" startid="#note-L30F1S3" endid="#note-L31F1S3" />
       <tie xml:id="tie-L31F1S1-L32F1S1" startid="#note-L31F1S1" endid="#note-L32F1S1" />
       <tie xml:id="tie-L31F1S2-L32F1S2" startid="#note-L31F1S2" endid="#note-L32F1S2" />
       <tie xml:id="tie-L31F1S3-L32F1S3" startid="#note-L31F1S3" endid="#note-L32F1S3" />
       <tie xml:id="tie-L32F1S1-L34F1S1" startid="#note-L32F1S1" endid="#note-L34F1S1" />
       <tie xml:id="tie-L32F1S2-L34F1S2" startid="#note-L32F1S2" endid="#note-L34F1S2" />
       <tie xml:id="tie-L32F1S3-L34F1S3" startid="#note-L32F1S3" endid="#note-L34F1S3" />
      </measure>
      <measure xml:id="measure-L33" right="end" n="11">
       <staff xml:id="staff-L33F1N1" n="1">
        <layer xml:id="layer-L33F1N1" n="1">
         <chord xml:id="chord-L34F1" dots="1" dur="1">
          <note xml:id="note-L34F1S1" oct="5" pname="f" accid.ges="n" />
          <note xml:id="note-L34F1S2" oct="5" pname="d" accid.ges="n" />
          <note xml:id="note-L34F1S3" oct="4" pname="b" accid.ges="n" />
         </chord>
        </layer>
       </staff>
       <fermata xml:id="fermata-L34F1" staff="1" startid="#chord-L34F1" place="above" />
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

**Comment by rettinghaus** [comment]
With proposed changes:
tiedchords

Everything should be fine, except for the edge case with the flag up note.

**Comment by craigsapp** [comment]
Looks great! Especially the barline avoidance enhancement (I am wondering about at barlines with decorations such as repeats and final barlines, which I will check in the future :-).

File: src/beam.cpp [hunk 1]
```diff
@@ -260,7 +260,7 @@ void BeamSegment::CalcBeamInit(
     // Calculate the extreme values
 
     int yMax = 0, yMin = 0;
-    int nbRests = 0;
+    size_t nbRests = 0;
```
Comment (craigsapp) [inline src/beam.cpp:263]: Just in case there will be more than [2147483647](https://en.wikipedia.org/wiki/2,147,483,647) rests... 😜

**Comment by craigsapp** [comment]
Now you will have to deal with the domino effect of mixing signed and unsigned integers 😜 

```
beam.cpp:320:22: warning: comparison of integers of different signs: 'int' and 'size_t'
      (aka 'unsigned long') [-Wsign-compare]
    if (elementCount != nbRests) {
```

File: src/beam.cpp (hunk 1 above)
Comment (lpugin) [reply src/beam.cpp:263]: Yes, why changing this? We use `int` everywhere in verovio and static cast to it when necessary (e.g. in `.size()`). This never cause any problem and is not likely to cause some.

Comment (lpugin) [reply src/beam.cpp:263]: Yes, why changing this? We use `int` everywhere in verovio and static cast to in when necessary (e.g. in `.size()`). This never cause any problem and is not likely to cause some.

Comment (rettinghaus) [reply src/beam.cpp:263]: Personally I think this would be more readable, but this one was actually connected to another thing, that has been fixed. Reverted it with #1720.
