### PR TITLE
PAE ties as elements

### LINKED ISSUE #820: Plaine & Easie: ties not working
PAE-ties (`+`) are only converted to attributes and thus not shown. They should be converted to `tie` elements instead.

### PR DESCRIPTION
**Pull request by rettinghaus**
fixes #820

### CODE REVIEW

File: src/iopae.cpp [hunk 1]
```diff
@@ -1317,17 +1319,15 @@ void PaeInput::parseNote(pae::Note *note)
...
+            m_tie = NULL;
         }
 
         if (note->tie) {
-            if (mnote->GetTie() == TIE_t)
-                mnote->SetTie(TIE_m);
-            else
-                mnote->SetTie(TIE_i);
-            m_last_tied_note = mnote;
+            m_tie = new Tie();
```
Comment (lpugin) [inline src/iopae.cpp]: You need to check in the PaeInput destructor if `m_tie == NULL` and delete it if not, otherwise there will be a memory leak.

File: src/iopae.cpp [hunk 2]
```diff
@@ -483,6 +486,7 @@ void PaeInput::parsePlainAndEasy(std::istream &infile)
         m_doc->m_scoreDef.SetProportNumbase(scoreDefMensur->GetNumbase());
         delete scoreDefMensur;
     }
+    if (m_tie != NULL) delete m_tie;
```
Comment (lpugin) [inline src/iopae.cpp]: Please set m_tie to NULL
